destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/sqvd-pdf"
port: 4010
output: pdf
product: SQVD
print_title: Jekyll theme for documentation â€” SQVD product
print_subtitle: version 1.0.0-pre
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: sqvd_sidebar
